### ISSUE TITLE
0.11.0 conda release

### ISSUE THREAD

**Issue by sgill2** [choderalab/openmmtools#228]
`openmmtools` 0.11.0 was released (very recently) on github, but the latest conda version is still on the previous release (0.10.0).

**Comment by jchodera** [comment]
@Lnaden : Can you tackle this?

**Comment by Lnaden** [comment]
There was a bit of confusion here caused by me. I made a PR called "Release 0.11.0" in #220, but did not cut a formal release on Github. So the name of the PR was a source of confusion. I cut the formal release today, pointing at the PR which made the change.

@jchodera yes, I'll cut the conda-recipe now

**Comment by Lnaden** [comment]
PR opened
