### ISSUE TITLE
Correctly copy our CustomIntegrator

### ISSUE THREAD

**Issue by andrrizzi** [choderalab/openmmtools#292]
I think we can make all our `CustomIntegrator` deepcopiable without losing the correct class and internal attributes by overriding the `openmm.Integrator.__copy__()` method with something like this.
```python
def __copy__(self):
    """Overwrite openmm.Integrator implementation to copy class and attributes."""
    integrator_copied = super(RestorableIntegrator, self).__copy__()

    # Assign correct class instead of CustomIntegrator.
    integrator_copied.__class__ = self.__class__

    # Copy attributes. CustomIntegrator has only 1 attribute (this),
    # everything else is part of the implementation.
    attributes_self = {k: v for k, v in self.__dict__.items() if k != 'this'}
    integrator_copied.__dict__.update(copy.deepcopy(attributes_self))

    return integrator_copied
```
I can add this very easily, but I'll **have to make the `LangevinIntegrator._registered_step_types` a class variable instead of an instance variable** because Python goes nuts when you try to deepcopy a `dict` containing a bound method and you get a `RecursionError`. Does this sound ok?

Note that the recently implemented pandegroup/openmm#1870 does not solve this particular problem.

**Comment by jchodera** [comment]
Is this a more general solution that could be implemented at the `openmm` level?

> I can add this very easily, but I'll have to make the LangevinIntegrator._registered_step_types a class variable instead of an instance variable because Python goes nuts when you try to deepcopy a dict containing a bound method and you get a RecursionError. Does this sound ok?

I'm not sure I fully understand the implications of this. There isn't a way to avoid this kind of thing in general if one wants to use instance variables?

I wonder if there's a more general solution we can build into the swig wrapper that can handle these issues by embedding the XML serialized C++ object inside a serialized Python object, rather than band-aiding the issue this way.

**Comment by andrrizzi** [comment]
> There isn't a way to avoid this kind of thing in general if one wants to use instance variables?

I don't think there is. The [Python docs for the `copy` module](https://docs.python.org/3.6/library/copy.html) says: "This module does not copy types like module, method, stack trace, ...". Copying bound methods is just not supported. The only other solution to this problem would be to explicitly override the `__copy__` method in `LangevinIntegrator` to avoid copying `self._registered_step_types` and re-register all the steps on the new object separately.

> Is this a more general solution that could be implemented at the `openmm` level?

I'm not sure actually. I wouldn't call this a band-aid solution anyway. This is exactly what Python does normally when copying an object. Only Python natively doesn't know how to copy a SWIG wrapper, and that's the part that is implemented here.

**Comment by jchodera** [comment]
> I can add this very easily, but I'll have to make the LangevinIntegrator._registered_step_types a class variable instead of an instance variable because Python goes nuts when you try to deepcopy a dict containing a bound method and you get a RecursionError. Does this sound ok?

OK, I think I had misunderstood. This change sounds fine.

Instead of changing the `LangevinIntegrator.__copy__`, would it make more sense just to add this to the [swig wrapper for `CustomIntegrator` in `pythoncode.i`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/src/swig_doxygen/swig_lib/python/pythoncode.i)? That way, all subclasses will benefit from copying, rather than just our `LangevinIntegrator`s.

**Comment by andrrizzi** [comment]
> would it make more sense just to add this to the swig wrapper for CustomIntegrator in pythoncode.i?

Sure, I'll try to make it work! I'll open an issue on openmm.
