### ISSUE TITLE
CI tests are failing

### ISSUE THREAD

**Issue by jchodera** [choderalab/openmmtools#468]
Any idea what is going on @dominicrufa @jaimergp ?

**Comment by jaimergp** [comment]
There are two issues going on:

* `!` marked tests failed due to to conda timeouts while reading the package metadata. Could be an intermittent issue because other tests did run.
* `X` marked tests failed due to:
    - unmatched arguments [here](https://travis-ci.org/github/choderalab/openmmtools/jobs/677250194#L3190). I doubt OpenMM changed their API so my guess is that whatever list of `parameters` we are unpacking at `force.addParticle(*parameters)` changed sizes somewhere upstream in the code?
    - on OSX, inability to [initialize the OpenCL platform](https://travis-ci.org/github/choderalab/openmmtools/jobs/677250195#L3312)
    - conda-forge packages have some [issues with Python itself](https://travis-ci.org/github/choderalab/openmmtools/jobs/677250197#L3023), maybe due to `defaults` vs `conda-forge` issues?

Seems that the diversity of errors is enough to justify the move to GH Actions for this repo too? I'd be happy to do it, but I think we should also consider teaching some more people how these transitions are done and how GH Actions works. Should we schedule a technical talk where I go through the conversion live? At least that way people can take notes, ask questions and then try themselves with another repo?

**Comment by jchodera** [comment]
> Seems that the diversity of errors is enough to justify the move to GH Actions for this repo too? I'd be happy to do it, but I think we should also consider teaching some more people how these transitions are done and how GH Actions works. Should we schedule a technical talk where I go through the conversion live? At least that way people can take notes, ask questions and then try themselves with another repo?

@jaimergp : Yes, can you do this and invite @dominicrufa @hannahbrucemacdonald and I and others to join?

**Comment by jaimergp** [comment]
Yes, I'll do! The OFF team is going to discuss details on their migration tomorrow, so I'll make sure we can join that collaborative effort once we agree on what features it could be interesting for the ecosystem.

**Comment by jaimergp** [comment]
Please note that PR #473 implements GHA and is awaiting review.

**Comment by jaimergp** [comment]
Most were solved by #473 and others. Closing this one.
