### ISSUE TITLE
openmmtools0.21.3 equilibration protocol forgets to broadcast _replica_thermodynamic_states

### ISSUE THREAD

**Issue by udlich** [choderalab/openmmtools#579]
In #562  PR, [ijpulidos](https://github.com/ijpulidos) modified the run() function in multistatesampler to broadcast _replica_thermodynamic_states, while in #556 [jfennick](https://github.com/jfennick) revised the equilibrate() function such that mixing was incorporated. Now there is a gap between the two revisions: in equilibrate() _replica_thermodynamic_states is not broadcasted.

**Comment by mikemhenry** [comment]
@ijpulidos can you take a look at this when you get a chance?

**Comment by udlich** [comment]
> @ijpulidos can you take a look at this when you get a chance?

This is indeed a very simple thing, just copy [ijpulidos](https://github.com/ijpulidos) code 'self._replica_thermodynamic_states = self._mix_replicas()' to equilibrate() section. I just want to remind everyone of this.

**Comment by ijpulidos** [comment]
@udlich Yes, this should be done for correctness, thanks for catching this! Just wanted to mention that in this case this is not too problematic since the `equilibrate()` method is not being run inside an MPI context (which was the original motivation for #562 ), as far as I can tell. But in any case, we should make sure the thermodynamic states are updated by appending that line. Thanks again!
