### ISSUE TITLE
Alchemical Regions do not Interact / Clarification

### ISSUE THREAD

**Issue by Dan-Burns** [choderalab/openmmtools#656]
In Alchemy.py `create_alchemical_system` has an option for alchemical_regions_interactions.

```
alchemical_regions_interactions : Set[Tuple[int, int]], optional
            Set of alchemical region index pairs for interacting regions.
            By default, all alchemical regions interact only with the
            non-alchemical environment.
```

If I'm modifying a whole protein for hremd, do I need to provide all possible pairs of protein atom indices?
Sorry for the confusion but I just came across this and began to wonder.

Thank you,
Dan

**Comment by Lnaden** [comment]
Its my understanding that its using the *alchemical region index* rather than the *particle index*, which is why its only 2 ints rather than a larger set of ints. Once a set of particles indicies has been assigned to an alchemical region, then that whole set can be tracked with the alchemical region index.

**Comment by Dan-Burns** [comment]
Thank you @Lnaden!  Seems like an obvious thing but thought it was worth checking.
