### ISSUE TITLE
Don't output nvidia-smi failure in automated platform search

### ISSUE THREAD

**Issue by IAlibay** [choderalab/openmmtools#693]
We've had folks a bit confused about this message showing up when they don't have a GPU device:

```
/bin/sh: nvidia-smi: command not found
```

Is there a way to avoid outputting this to users?

**Comment by mikemhenry** [comment]
Yes, I think checking the error code https://github.com/choderalab/openmmtools/blob/abd4011f1c756722ab8671097335c0e895f5741f/openmmtools/multistate/multistatesampler.py#L1774-L1780 and if it fails, we can output something like "No GPU detected" since that is more clear with what is going on.

**Comment by mikemhenry** [comment]
Actually all we need to do is capture the output of the os.popen call and not have it dump to std err

**Comment by mikemhenry** [comment]
I can fix this

**Comment by mikemhenry** [comment]
@ijpulidos Why do we split by comma? `# Split by line jump and comma` I am using a slightly different method to invoke the subprocess call to `nvidia-smi` and the captured output looks like `'0, NVIDIA GeForce RTX 3060 Laptop GPU\n'` So I was thinking we would want to save it like `0, NVIDIA GeForce RTX 3060 Laptop GPU` (in a list) so that users know the GPU index, thoughts?
